### ISSUE TITLE
Hermex/WebUI: stale process after hermes update causes module version skew

### ISSUE THREAD

**Issue by 100yenadmin** [electricsheephq/lcm-x#58]
> [!IMPORTANT]
> This is the active LCM-X continuation of an open upstream issue. The imported comments below preserve attributed discussion; historical GitHub actors and timestamps were not transferred.

## Source and attribution

- Original issue: [https://github.com/stephenschoettler/hermes-lcm/issues/433](https://github.com/stephenschoettler/hermes-lcm/issues/433)
- Originally authored by @ryetaylor406
- Upstream author profile: [ryetaylor406](https://github.com/ryetaylor406)
- Preservation receipt: [https://github.com/electricsheephq/lcm-x/issues/58](https://github.com/electricsheephq/lcm-x/issues/58)
- Frozen upstream update: `2026-07-22T23:15:55Z`

### Problem

After upgrading Hermes Agent from v0.18 to v0.19, the Hermex WebUI (separate `~/hermes-webui/` process) failed to start new sessions with:

- `ImportError: cannot import name '_compression_warrants_another_preflight_pass' from 'agent.turn_context'`
- `TypeError: ContextCompressor.__init__() got an unexpected keyword argument 'model_thresholds'`
- Gateway log: `Context engine 'lcm' not found — falling back to built-in compressor`

Desktop and Telegram sessions worked fine.

### Root Cause

The WebUI is a **separate long-running process** from the gateway. After `hermes update`, the WebUI still had v0.18 Python modules cached in `sys.modules`. New on-disk files mixed with old cached ones at lazy-import time. Six attempted fixes (gateway restarts, symlinks, wrapper, core patch, bytecode clear, PWA cache clear) all failed because they targeted the wrong process.

### Fix

```bash
~/hermes-webui/ctl.sh restart
```

That was it. The WebUI process had been running 5 days 21 hours.

### Prevention

Added `WatchPaths` to the WebUI launchd plist to auto-restart when hermes-agent files change:

```xml
<key>WatchPaths</key>
<array>
    <string>/Users/rye/.hermes/hermes-agent/agent/agent_init.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/context_compressor.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/turn_context.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/conversation_loop.py</string>
</array>
```

### Recommendation

Consider documenting: "After `hermes update`, restart the WebUI and the gateway." Or add a post-install hook. Longer-term: shipping `hermes-lcm` as a pip-installable package would eliminate the module-path/import issues that make this kind of version skew possible — plugins in `site-packages` survive agent updates cleanly.

### Environment

- macOS 26.3.1, Mac mini M4
- Hermes Agent v0.19.0 (upgraded from v0.18)
- hermes-lcm v0.19.0 (git cloned, main branch)
- WebUI at `~/hermes-webui/` on port 8787

Thanks for the plugin. The DAG summaries are excellent. Just want to help other Hermex users avoid the same debugging session.

## Continuation state

This issue is open for ongoing LCM-X triage and work. Existing imported comments retain the attributed upstream discussion. New LCM-X decisions and implementation should continue here.

**Comment by 100yenadmin** [comment]
### Imported upstream original-body

- Original author: [ryetaylor406](https://github.com/ryetaylor406)
- Original date: `2026-07-22T23:15:55Z`
- Original location: [https://github.com/stephenschoettler/hermes-lcm/issues/433](https://github.com/stephenschoettler/hermes-lcm/issues/433)

### Problem

After upgrading Hermes Agent from v0.18 to v0.19, the Hermex WebUI (separate `~/hermes-webui/` process) failed to start new sessions with:

- `ImportError: cannot import name '_compression_warrants_another_preflight_pass' from 'agent.turn_context'`
- `TypeError: ContextCompressor.__init__() got an unexpected keyword argument 'model_thresholds'`
- Gateway log: `Context engine 'lcm' not found — falling back to built-in compressor`

Desktop and Telegram sessions worked fine.

### Root Cause

The WebUI is a **separate long-running process** from the gateway. After `hermes update`, the WebUI still had v0.18 Python modules cached in `sys.modules`. New on-disk files mixed with old cached ones at lazy-import time. Six attempted fixes (gateway restarts, symlinks, wrapper, core patch, bytecode clear, PWA cache clear) all failed because they targeted the wrong process.

### Fix

```bash
~/hermes-webui/ctl.sh restart
```

That was it. The WebUI process had been running 5 days 21 hours.

### Prevention

Added `WatchPaths` to the WebUI launchd plist to auto-restart when hermes-agent files change:

```xml
<key>WatchPaths</key>
<array>
    <string>/Users/rye/.hermes/hermes-agent/agent/agent_init.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/context_compressor.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/turn_context.py</string>
    <string>/Users/rye/.hermes/hermes-agent/agent/conversation_loop.py</string>
</array>
```

### Recommendation

Consider documenting: "After `hermes update`, restart the WebUI and the gateway." Or add a post-install hook. Longer-term: shipping `hermes-lcm` as a pip-installable package would eliminate the module-path/import issues that make this kind of version skew possible — plugins in `site-packages` survive agent updates cleanly.

### Environment

- macOS 26.3.1, Mac mini M4
- Hermes Agent v0.19.0 (upgraded from v0.18)
- hermes-lcm v0.19.0 (git cloned, main branch)
- WebUI at `~/hermes-webui/` on port 8787

Thanks for the plugin. The DAG summaries are excellent. Just want to help other Hermex users avoid the same debugging session.

**Comment by 100yenadmin** [comment]
**Triage: verified still live on `origin/main` during a full backlog sweep.**

Recorded so this issue carries a disposition rather than sitting unexamined, and so a future sweep does not close it on a symbol-level match. The per-issue evidence — the exact `file:line` read, whether each cited symbol is actually *called* rather than merely defined, and what the check does not prove — is in the lane's verification record:

`session-notes/2026-08-20/lcmx-maintainer/artifacts/verify-issues-batch4.md`

**Why the record matters more than the verdict here.** Across three sweeps this backlog has repeatedly looked more fixed than it is: an adversarial recheck refuted 5 of 17 "already satisfied" claims, a later batch found 13 of 14 still live, and three issues in this batch turned out to be *partially* answered under a different name than the issue used (#48, #53, #72). A bare "still open" is worth little; the reasoning is what stops the next person redoing the work or closing it wrongly.

**Proof boundary:** static source inspection of `origin/main`. Nothing was executed, so this establishes that the code does not implement the ask — not that the reported symptom reproduces at runtime.

No action taken on the issue itself. Priority order in this lane is external contributions → correctness and data-loss fixes → issues with reproducible claims → feature drafts, so feature-shaped items sit behind the correctness work rather than being abandoned.
